version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    # Port non exposé volontairement

  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "8080:80"  # Expose seulement l'app NextCloud
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_HOST: db
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      - nextcloud-net

volumes:
  postgres-data:
  nextcloud-data:

networks:
  nextcloud-net:
